version: '3'

services:
  # client:
  #   depends_on:
  #     - server
  #   build: ./client
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - BACKEND_URL: http://server:5000

  # chatbot:
  #   depends_on:
  #     - server
  #   build: ./chatbot
  #   ports:
  #     - '7000:7000'
  #   environment:
  #     BACKEND_URL: http://server:5000

  client_admin:
    depends_on:
      - server
    build: ./client_admin
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_ADMIN_USERID=admin
      - REACT_APP_ADMIN_PASSWORD=conculan

  server:
    depends_on:
      - database
    build: ./server
    ports:
      - '5000:5000'
    environment:
      - CHATBOT_SERVER_URL=http://chatbot:7000
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/postgres

  database:
    build: ./database
    ports:
      - '5432:5432'
    volumes:
      - ./database/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=UTC+7
