version: "3"


services:

  # client:
  #   depends_on: 
  #     - server
  #   build: ./client
  #   ports: 
  #     - "3000:3000"
  #   environment: 
  #     - BACKEND_URL: http://server:5000

  chatbot:
    depends_on: 
      - server
    build: ./chatbot
    ports:
      - "7000:7000"
    environment: 
      BACKEND_URL: http://server:5000

  server:
    depends_on: 
      - database
    build: ./server
    ports: 
      - "5000:5000"
    environment: 
      CHATBOT_SERVER_URL: http://chatbot:7000

  database:
    image: postgres

